[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:regulatory-service]
command=java %(ENV_JAVA_OPTS)s -jar /app/regulatory-service.jar --server.port=8090
autostart=true
autorestart=true
priority=1
startsecs=10
stdout_logfile=/var/log/regulatory-service.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/var/log/regulatory-service-error.log
stderr_logfile_maxbytes=10MB
environment=SPRING_PROFILES_ACTIVE="server2"

[program:ingestion-service]
command=java %(ENV_JAVA_OPTS)s -jar /app/ingestion-service.jar --server.port=8083 --spring.profiles.active=forex,server2
autostart=true
autorestart=true
priority=2
startsecs=30
stdout_logfile=/var/log/ingestion-service.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/var/log/ingestion-service-error.log
stderr_logfile_maxbytes=10MB
