server:
  port: ${SERVER_PORT:8092}
  id: ${SERVER_ID:server1}

spring:
  application:
    name: check-eligible-service

eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.id}:${server.port}
    metadata-map:
      server-id: ${server.id}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8088/eureka}
    registry-fetch-interval-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.bmo.rdp: DEBUG
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
