[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:refdata-service]
command=java %(ENV_JAVA_OPTS)s -jar /app/refdata-service.jar --server.port=8081
autostart=true
autorestart=true
priority=1
startsecs=10
stdout_logfile=/var/log/refdata-service.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/var/log/refdata-service-error.log
stderr_logfile_maxbytes=10MB
environment=SPRING_PROFILES_ACTIVE="server3"

[program:eligibility-service]
command=java %(ENV_JAVA_OPTS)s -jar /app/eligibility-service.jar --server.port=8092
autostart=true
autorestart=true
priority=1
startsecs=10
stdout_logfile=/var/log/eligibility-service.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/var/log/eligibility-service-error.log
stderr_logfile_maxbytes=10MB
environment=SPRING_PROFILES_ACTIVE="server3"

[program:ingestion-service]
command=java %(ENV_JAVA_OPTS)s -jar /app/ingestion-service.jar --server.port=8082 --spring.profiles.active=irswap,server3
autostart=true
autorestart=true
priority=2
startsecs=30
stdout_logfile=/var/log/ingestion-service.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/var/log/ingestion-service-error.log
stderr_logfile_maxbytes=10MB
